- name: Download dotfiles
  shell: git clone https://github.com/3/dotfiles --recursive

- name: Create Symbolic link
  file: src=/home/tmux/dotfiles/{{ item.path }} dest=/home/tmux/{{ item.dest }} state=link
  with_items:
    - { path: '.vim', dest: '.vim' }
    - { path: '.vimrc', dest: '.vimrc' }
    - { path: '.tmux.conf', dest: '.tmux.conf' }
    - { path: '.gitconfig', dest: '.gitconfig' }
